#if !canImport(ObjectiveC)
import XCTest

extension AWSXRayRecorderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AWSXRayRecorderTests = [
        ("testRecordingOneSegment", testRecordingOneSegment),
        ("testRecordingOneSegmentClosure", testRecordingOneSegmentClosure),
    ]
}

extension AWSXRaySegmentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AWSXRaySegmentTests = [
        ("testSegmentInvalidId", testSegmentInvalidId),
        ("testSegmentRandomId", testSegmentRandomId),
    ]
}

extension AWSXRayTraceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AWSXRayTraceTests = [
        ("testTraceHeaderInvalidFormat", testTraceHeaderInvalidFormat),
        ("testTraceHeaderInvalidParent", testTraceHeaderInvalidParent),
        ("testTraceHeaderInvalidRoot", testTraceHeaderInvalidRoot),
        ("testTraceHeaderNoParentSampled", testTraceHeaderNoParentSampled),
        ("testTraceHeaderWithParentNotSampled", testTraceHeaderWithParentNotSampled),
        ("testTraceHeaderWithParentSampled", testTraceHeaderWithParentSampled),
        ("testTraceHeaderWithParentUnkownRequestedSample", testTraceHeaderWithParentUnkownRequestedSample),
        ("testTraceHeaderWithParentUnkownUnkownSample", testTraceHeaderWithParentUnkownUnkownSample),
        ("testTraceOldId", testTraceOldId),
        ("testTraceOverflowId", testTraceOverflowId),
        ("testTraceRandomId", testTraceRandomId),
        ("testTraceRandomIdenifier", testTraceRandomIdenifier),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    [
        testCase(AWSXRayRecorderTests.__allTests__AWSXRayRecorderTests),
        testCase(AWSXRaySegmentTests.__allTests__AWSXRaySegmentTests),
        testCase(AWSXRayTraceTests.__allTests__AWSXRayTraceTests),
    ]
}
#endif
