#if !canImport(ObjectiveC)
import XCTest

extension AWSXRayRecorderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AWSXRayRecorderTests = [
        ("testRecordingOneSegment", testRecordingOneSegment),
        ("testRecordingOneSegmentClosure", testRecordingOneSegmentClosure),
    ]
}

extension AWSXRaySegmentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AWSXRaySegmentTests = [
        ("testSegmentInvalidId", testSegmentInvalidId),
    ]
}

extension AWSXRayTraceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AWSXRayTraceTests = [
        ("testTraceHeaderInvalidFormat", testTraceHeaderInvalidFormat),
        ("testTraceHeaderInvalidParent", testTraceHeaderInvalidParent),
        ("testTraceHeaderInvalidRoot", testTraceHeaderInvalidRoot),
        ("testTraceHeaderNoParentSampled", testTraceHeaderNoParentSampled),
        ("testTraceHeaderWithParentNotSampled", testTraceHeaderWithParentNotSampled),
        ("testTraceHeaderWithParentSampled", testTraceHeaderWithParentSampled),
        ("testTraceHeaderWithParentUnkownRequestedSample", testTraceHeaderWithParentUnkownRequestedSample),
        ("testTraceHeaderWithParentUnkownUnkownSample", testTraceHeaderWithParentUnkownUnkownSample),
        ("testTraceOldId", testTraceOldId),
        ("testTraceOverflowId", testTraceOverflowId),
        ("testTraceRandomId", testTraceRandomId),
    ]
}

extension NIOHelpersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NIOHelpersTests = [
        ("testSocketAddressParsingInvalidIpAddress", testSocketAddressParsingInvalidIpAddress),
        ("testSocketAddressParsingInvalidPort", testSocketAddressParsingInvalidPort),
        ("testSocketAddressParsingNoPort", testSocketAddressParsingNoPort),
        ("testSocketAddressParsingPositive", testSocketAddressParsingPositive),
    ]
}

extension RandomTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RandomTests = [
        ("testRandom64", testRandom64),
        ("testRandom96", testRandom96),
    ]
}

extension TimestampTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TimestampTests = [
        ("testTimestampAgainstFoundation", testTimestampAgainstFoundation),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    [
        testCase(AWSXRayRecorderTests.__allTests__AWSXRayRecorderTests),
        testCase(AWSXRaySegmentTests.__allTests__AWSXRaySegmentTests),
        testCase(AWSXRayTraceTests.__allTests__AWSXRayTraceTests),
        testCase(NIOHelpersTests.__allTests__NIOHelpersTests),
        testCase(RandomTests.__allTests__RandomTests),
        testCase(TimestampTests.__allTests__TimestampTests),
    ]
}
#endif
