name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: OS name
      run: uname -a
    - name: Swift version
      run: swift --version
    - name: Build
      run: swift build

  build-examples:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: OS name
      run: uname -a
    - name: Swift version
      run: swift --version
    - name: Build Examples
      run: swift build
      working-directory: ./Examples
    - name: Print shared libraries
      if: ${{ matrix.platform == 'ubuntu-latest' }}
      run: ldd .build/debug/AWSXRaySDKExample
      working-directory: ./Examples
