name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: OS name
      run: uname -a
    - name: Swift version
      run: swift --version
    - name: Build
      run: swift build -c release

  examples:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: OS name
      run: uname -a
    - name: Swift version
      run: swift --version
    - name: Build Examples
      run: swift build -c release
      working-directory: ./Examples
    - name: Print shared libraries
      run: ldd .build/release/AWSXRaySDKExample
      working-directory: ./Examples
  