name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  lint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install swiftformat
      run: brew install swiftformat
    - name: Run lint
      run: swiftformat --lint .
  
  examples:

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Build Examples
      run: swift build -v
      working-directory: ./Examples
