name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test-macos:
    runs-on: macos-latest  

    steps:
    - uses: actions/checkout@v2
    - name: OS name
      run: uname -a
    - name: Swift version
      run: swift --version
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test --enable-code-coverage
    - name: Generate coverage report
      run: xcrun llvm-cov export -format="lcov" .build/debug/aws-xray-sdk-swiftPackageTests.xctest/Contents/MacOS/aws-xray-sdk-swiftPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: info.lcov
    - name: Run Performance tests
      run: swift test -c release --enable-test-discovery
      working-directory: ./PerformanceTests

  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images:
        - swift:5.2-amazonlinux2
    container:
      image: ${{ matrix.images }}

    steps:
    - uses: actions/checkout@v2
    - name: OS name
      run: uname -a
    - name: Swift version
      run: swift --version
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test --enable-test-discovery --enable-code-coverage
    - name: Generate coverage report
      run: llvm-cov export -format="lcov" .build/x86_64-unknown-linux-gnu/debug/aws-xray-sdk-swiftPackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Install curl using apt-get
      if: ${{ matrix.images == 'swift:5.2' }}
      run: apt-get update && apt-get -y install curl # required by codecov-action
    - name: Install curl using yum
      if: ${{ matrix.images == 'swift:5.2-amazonlinux2' }}
      run: yum -y install curl # required by codecov-action
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: info.lcov
    - name: Run Performance tests
      run: swift test -c release --enable-test-discovery
      working-directory: ./PerformanceTests
